version: '3.8'

networks:
  app-network:

services:
  webserver:
    image: nginx:1.21.6-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./build:/usr/share/nginx/html
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      app-network:
  
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: app
    tty: true
    networks:
      - app-network